### PR TITLE
Added the newly renovated Beaulieu Theatre

### PR DESCRIPTION
**Pull request by MarkJaroski**
They do date spans sometimes, and so far I've only been able to work out how to pick up the last date in the run. There might be some way to do it with a regex but I haven't worked it out just yet.

### CODE REVIEW

**Comment by jakopako** [comment]
I'm afraid that right now there is no way to properly cope with those date spans. Right now, goskyr doesn't allow for a single item to translate to multiple events in the output. I might need to add some functionality that allows this. Suggestions are of course welcome!

For now I'll merge this pr at the cost of missing some of the events.

**Comment by jakopako** [comment]
I moved the date extraction to the subpage so that we're able to extract the time, too.

**Comment by MarkJaroski** [comment]
> I'm afraid that right now there is no way to properly cope with those date spans. Right now, goskyr doesn't allow for a single item to translate to multiple events in the output. I might need to add some functionality that allows this. Suggestions are of course welcome!
> 
> For now I'll merge this pr at the cost of missing some of the events.

I'll give it some thought.

**Comment by MarkJaroski** [comment]
FWIW the venue is magnificent

**Pull request merged**
