### PR TITLE
Bleu Lézard finally has a real website !

### PR DESCRIPTION
**Pull request by MarkJaroski**

### CODE REVIEW

**Comment by jakopako** [comment]
This is interesting! I think all events that start at midnight actually have a wrong date. For instance the event on Friday, 15.12.2023 at 00:00, which I guess is starting during the night from Friday to Saturday. However, the (technically correctly) scraped date suggests that the event takes place during the night from Thursday to Friday. I'm not sure what to do with this. I tend to having the correct date in the database, and then applications that use that data can do with it what they want. The problem is that we'd need to somehow add 24 hours to the scraped date, which is currently not possible.

I think I'd also be fine with having the wrong data in the database for now until there is additional functionality in goskyr that would allow date manipulation. What do you think?

**Comment by MarkJaroski** [comment]
I wish I had noticed that. I did notice what looked like an anomaly with one a festival event there that we picked up earlier in the year... I'll examine the situation.

**Comment by MarkJaroski** [comment]
We could subtract one minute from the start time, and that would get it consistently pretty close to right, no?

**Comment by MarkJaroski** [comment]
So this converts any 00:00 time to 11:59, which probably works, no?

**Comment by jakopako** [comment]
Yes, this works! Awesome solution, I like it!

**Pull request merged**
