### PR TITLE
Added this clasic ska/britpop venue

### PR DESCRIPTION
**Pull request by MarkJaroski**

### CODE REVIEW

**Comment by jakopako** [comment]
Hey @MarkJaroski why did you close this PR?

**Comment by MarkJaroski** [comment]
Slip of the mouse?

**Comment by MarkJaroski** [comment]
I think maybe the second commit did it somehow.

**Comment by jakopako** [comment]
Alright, merged it. I added the `guess_year` option to the date field to make sure the year is correct, even around end/beginning of a year. Also had to make this mechanism more robust in goskyr, which is why I updated the version in the github action.

**Pull request merged**
