### PR TITLE
Add explicit year to JazzOnze to prevent spurious listings for 2024

### PR DESCRIPTION
**Pull request by MarkJaroski**
We'll have to update this in the fall of course. Perhaps I will drop them a line to suggest that they include the year consistently next year.

### CODE REVIEW

**Comment by jakopako** [comment]
Thanks, good catch! I recently cleaned up a bunch of venues that had the wrong year in the scraped results but I missed this one. 

I actually made a change to your pr in the hopes that this config won't need an update in autumn 🤞 Hope that's ok :)

**Comment by jakopako** [comment]
I will also clean up the DB and remove those spurious listings.

**Comment by MarkJaroski** [comment]
I tried to use the class attribute and couldn't get it to work. I thought maybe since class is part of the selector it wouldn't.

So I'll have a look at how you did it for next time this kind of thing comes up.

**Comment by jakopako** [comment]
To be honest, I was confused at first too because after I used the class attribute I got 0 events.. then I realized that there's a filter that removes events with date < now 😅

**Comment by MarkJaroski** [comment]
Right!

**Pull request merged**
