### PR TITLE
Added Humbug which seems to be the happening place in Basel

### PR DESCRIPTION
**Pull request by MarkJaroski**
This isn't as fresh in my mind as one would like, so I might have made some mistakes.

Given the range of possible date formats the config is pretty noisy.

### CODE REVIEW

**Comment by jakopako** [comment]
Thank you for your effort!

There is a problem with this venue's website, that the current version of goskyr cannot handle, I'm afraid. The website contains a LOT of past events that have the exact same css selector, so goskyr currently cannot distinguish between future and past events on this website. The fact that the resulting list of events is not ordered by date (it's like 1 2 3 4 1 0 -1 -2... if 0 is the current date) combined with the rather simple approach of how data is currently written to the database also doesn't increase my confidence that this specific case wouldn't break anything at some point.

I have to think about potential solutions. Of course any input from your side is welcome! I'm thinking that maybe some kind of filter functionality extension where you can filter on the data field (eg date > now) might be a way to solve this.

**Comment by MarkJaroski** [comment]
I think there's at least one decent argument for supporting archival events: important memories. People meet their significant others at concerts. Other amazing things in their lives happen around concert attendance.

I can see why you wouldn't want indefinite db growth, but the past can be useful.

**Comment by jakopako** [comment]
I totally agree that it's nice to have past events as well! And that's actually the case already albeit a bit hidden. On the website you can narrow down the search to any date in the past and you'll get the corresponding events. Currently, it is not an issue that the data keeps growing as it's still very little (a couple of mb for ~30k concerts)

What I meant was rather that we might readd the same past events over and over again with the (small) risk of creating duplicates and hence increasing the amount of data unnecessarily and polluting the db. As soon as I have time I'll check if that's the case. I probably didn't explain the issue well, but as I said, the current way data is written to the db is possibly not the most robust way.

**Comment by MarkJaroski** [comment]
I see! That makes more sense.

**Comment by jakopako** [comment]
I've finally done some testing and there shouldn't be any issues. Worst case, I'll have to delete some stuff directly in the database but the chances are very small I think.

**Pull request merged**
