### PR TITLE
BeJazz have asked us to stop scraping. Let's do that while we talk with

### PR DESCRIPTION
**Pull request by MarkJaroski**
them. See #323.

It's sad. :(

### CODE REVIEW

**Comment by jakopako** [comment]
:/ thanks for the pr. Although it's sad that they don't want to scraped. Understandable though. I'll look into what exactly went wrong as soon as I can and will also purge the wrong events.

**Comment by MarkJaroski** [comment]
I think you may have already fixed it in December. The false October and November events are no longer there.

**Comment by MarkJaroski** [comment]
I've been checking everything else more than six months in the future, and they all check out. I still don't understand what went wrong with BeJazz.

**Comment by jakopako** [comment]
Yeah, I fixed it in commit https://github.com/jakopako/croncert-config/commit/145a9d93d0a2f39444822f8077155c00031dfb9f I think. As soon as it got fixed the wrong events were deleted automatically, due to my approach of always deleting all future events in the DB before adding new ones.

**Pull request merged**
