### PR TITLE
Added the Rounhouse concert venue

### PR DESCRIPTION
**Pull request by MarkJaroski**

### CODE REVIEW

**Comment by jakopako** [comment]
Hey @MarkJaroski thanks for this addition! I added a suggestion for stricter filtering. There were some events that were not really concerts and that spanned a couple of days in one entry. So the date in the scraped events was only a tiny fraction of all dates for these events.
I think you'd tend towards adding these events nonetheless because you're more on the 'include everything' side whereas I'm more on the 'only concerts' side :D So feel free to contradict :)

**Comment by MarkJaroski** [comment]
I think that's reasonable. The word Concert is in the name of the site after all.

I do wish there were a good way to capture events spanning multiple days, however. Sometimes these are actual concerts in fact.

**Comment by jakopako** [comment]
You're right, that feature is missing right now. I haven't really thought about this problem in detail and I think there are many different shapes and forms that these multi day events can take.

**Comment by jakopako** [comment]
Tried to capture it here: https://github.com/jakopako/goskyr/issues/276

**Comment by jakopako** [comment]
I'll merge this pr for now. But maybe we could think of some kind of hack using the transform feature to make the type field dynamic. Ie use the same selector as for the title and then transform to X if it matches certaim expressions and default to concert. Not sure though if this exact functionality would already be supported by the current transform implementation. If i'm not mistaken it just applies the entire list of transforms. We'd rather need sth that loops over the list but stops as soon as it matches, with the last entry being the default (maybe match .* or sth). A bit like a switch case

**Comment by MarkJaroski** [comment]
I'm doing something like this to feed the Mobilizòn (https://mobilisons.ch) uploader when I feed it from a flat file created by goskyr, since of course mobilisons.ch is about more than concerts.

I'm thinking about switching to use goskyr as a libray for the bot, in fact.

Here's my first attempt at doing a goskyr config for the bot:

https://github.com/MarkJaroski/ConcertCloudMobilizonBot/blob/main/goskyr-config/reflet.yml

**Comment by jakopako** [comment]
Nice! Does mobilizon have fixed categories? Or do you decide that?

**Comment by MarkJaroski** [comment]
> Nice! Does mobilizon have fixed categories? Or do you decide that?

They're fixed. Here's the current list:

```golang
type EventCategory string

const (
	ARTS                          EventCategory = "ARTS"
	AUTO_BOAT_AIR                 EventCategory = "AUTO_BOAT_AIR"
	BOOK_CLUBS                    EventCategory = "BOOK_CLUBS"
	BUSINESS                      EventCategory = "BUSINESS"
	CAUSES                        EventCategory = "CAUSES"
	COMEDY                        EventCategory = "COMEDY"
	COMMUNITY                     EventCategory = "COMMUNITY"
	CRAFTS                        EventCategory = "CRAFTS"
	FAMILY_EDUCATION              EventCategory = "FAMILY_EDUCATION"
	FASHION_BEAUTY                EventCategory = "FASHION_BEAUTY"
	FILM_MEDIA                    EventCategory = "FILM_MEDIA"
	FOOD_DRINK                    EventCategory = "FOOD_DRINK"
	GAMES                         EventCategory = "GAMES"
	HEALTH                        EventCategory = "HEALTH"
	LANGUAGE_CULTURE              EventCategory = "LANGUAGE_CULTURE"
	LEARNING                      EventCategory = "LEARNING"
	LGBTQ                         EventCategory = "LGBTQ"
	MEETING                       EventCategory = "MEETING"
	MOVEMENTS_POLITICS            EventCategory = "MOVEMENTS_POLITICS"
	MUSIC                         EventCategory = "MUSIC"
	NETWORKING                    EventCategory = "NETWORKING"
	OUTDOORS_ADVENTURE            EventCategory = "OUTDOORS_ADVENTURE"
	PARTY                         EventCategory = "PARTY"
	PERFORMING_VISUAL_ARTS        EventCategory = "PERFORMING_VISUAL_ARTS"
	PETS                          EventCategory = "PETS"
	PHOTOGRAPHY                   EventCategory = "PHOTOGRAPHY"
	SCIENCE_TECH                  EventCategory = "SCIENCE_TECH"
	SPIRITUALITY_RELIGION_BELIEFS EventCategory = "SPIRITUALITY_RELIGION_BELIEFS"
	SPORTS                        EventCategory = "SPORTS"
	THEATRE                       EventCategory = "THEATRE"
)

```

**Pull request merged**
