### PR TITLE
Chorus, the main Jazz club in Lausanne

### PR DESCRIPTION
**Pull request by MarkJaroski**
This one was easy for a change. I hope I got all the fields right this time.

### CODE REVIEW

**Comment by jakopako** [comment]
Thanks a lot!

I'm getting some errors when running this. Sometimes the string that you're using for the date right now seems to include the price as well. Do you mind fixing this with a regex?

**Comment by MarkJaroski** [comment]
Happily!

**Comment by MarkJaroski** [comment]
I think this may have been another Fév issue. I wonder if we'll see this again in Août.

**Comment by jakopako** [comment]
Yeah we'll see. I'm thinking that once we have a working regex-replace functionality in goskyr we could remove the hacks and move the responsibility of providing a correct date (by using the regex-replace func where necessary) to the person configuring the date.

**Comment by jakopako** [comment]
Thanks again for your contribution. I absolutely love that you're putting so much effort into this!

**Comment by MarkJaroski** [comment]
Happy to help!

I'm internally motivated. I don't want to rely on a dozen websites to find all the concerts within a reasonable distance, or on my wife's use of Facebook events.

So I searched for a github project doing event scraping, and lo and behold there you were, in Switzerland no less.

**Pull request merged**
